### ISSUE TITLE
Speed up CI runs

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#3352]
CI runs take ~3.5h by now, so we only get through ~7 per day. The majority of the time is (unsurprisingly) spent building tests (~1.5h) and executables (~1h). Does anyone have ideas how we could speed things up?

Here's a few thoughts:

- [x] (resolved by #3366) Caching seems to be quite ineffective, I see only very low hit rates of a few percent. It has worked better in the past. We can probably improve it by a combination of debugging ccache in the build system and debugging how caches are handled by GitHub Actions. I think GitHub has increased the available storage to <s>5GB</s> 10GB a while ago, so perhaps we can take better advantage of this.
- [ ] Increasing the available space for caches from the current max of 5GB to ~15GB could significantly improve effectiveness of caching, because all build configurations could be stored. GitHub doesn't allow this (as of Aug 2021). Edit Jun 2022: cache size is now 10GB.
- [ ] Reducing the number of builds in the Compiler x {Debug,Release} matrix, or something like #3270, would increase throughput by a lot -- can we remove some of the builds without compromising the effectiveness of the tests?
- [x] #3351 should help with throughput as well.
- [ ] We could pay for more concurrent GitHub-hosted runners, or set up some self-hosted runners on a cluster like Minerva. Self-hosted runners would also enable us to run multi-node tests occasionally (e.g. on-request and once a month before a release).

**Comment by nilsdeppe** [comment]
I would expect caching to help on repeated develop runs. We may want to disable saving the cache completely on PR builds since people won't be rebasing very frequently (as in, every time a PR is merged), instead using the cache from develop. Then encouraging people to rebase before pushing to their PR should work quite well.

I'm also very optimistic that #3351 will provide a pretty big boost since it's not uncommon for people to push several times when doing fixups, and then CI builds all of the different copies (or at least tries to).

**Comment by wthrowe** [comment]
Ideas from today's meeting:
* Caching should work better than it is.
* Have fewer executables, e.g., by merging numerical vs. analytic initial data.

**Comment by nilsvu** [comment]
Here are the plots I showed in a call recently:

![ci_runs_clang](https://user-images.githubusercontent.com/746230/128085448-59199c17-e062-41cb-80be-f5110a227b74.png)
![ci_runs_gcc](https://user-images.githubusercontent.com/746230/128085482-a526149d-6588-4315-96ce-baea922dbf31.png)

The dotted lines are at:

- 2020-04-10 (maybe #2193)
- 2020-11-20 (probably #2555)
- 2021-01-05 (no idea)

---

The recent PRs around #3366 and #3351  were quite effective in speeding up CI, so I consider this issue resolved (for now).

**Comment by nilsdeppe** [comment]
The third point in the checklist is addressed in #4019 where I reduce the number of clang builds. I think being thorough with GCC is good for the time being since that's the main compiler used on HPC systems.
