### ISSUE TITLE
Improvements for the BinaryCompactObject domain

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#3545]
# Feature request:

From experiments with elliptic solves on our `BinaryCompactObject` domain I find that it currently needs about twice as many grid points as the SpEC initial data domain to reach the same accuracy (a bit worse actually). Here's some details, and suggestions for improvements that we can discuss:

- The **radial** distribution of grid points seems mostly fine, except the two inner cubes and the enveloping cube-to-sphere could be improved with a logarithmic or 1/r radial map.
- The **angular** direction has three problems:
  - [x] 1. Blocks vary a lot in angular size, since in +x and -x direction a single block covers the same angular size that is covered by two blocks in the y/z directions. This means to get a uniform domain we have to h-refine all blocks once in azimuthal direction, and the +/-x blocks also once in polar direction. This introduces many grid points that would be more effectively spent on p-refinement, and some unavoidable h-nonconforming boundaries. Edit: #3941 is a partial step towards this. Still needs to be activated for BBH domain. Edit2: #4934 implements this.
  - [x] 2. Equiangular maps are currently not implemented. Tests on the Cylinder showed that equiangular maps help significantly to increase angular resolution. Edit: done in #4676.
  - [x] 3. The transitions from spheres to cubes to enveloping cube to sphere introduce angular Jacobians that the code needs to resolve, and additional grid points. The two inner spheres-to-cubes seem fine in my tests since they do a lot of the work of resolving the physical features. But the enveloping cube-to-sphere introduces a layer of grid points that aren’t as effective. I think a big optimization would be to remove the enveloping cube altogether, and transition from the two inner cubes to a sphere right away. Edit: done in #3882.

Here's the slice through the current BBH domain for reference:

![Bildschirmfoto 2021-09-23 um 18 07 50](https://user-images.githubusercontent.com/746230/134543761-51d97363-67f0-4c48-bd6d-0c3bb6a3e0a4.png)

**Comment by mar-celine** [comment]
Summary of a chat between me and @nilsleiffischer :

There is a path to address these issues that involves a new mapping for the Frustum blocks in the domain.
A: **angular ii**  can be addressed by adding equiangular mapping functionality to the Frustum maps. This is non-trivial because the domain requires that the inner face of a Frustum map (closest to the black holes) use the full [-1,1] equiangular map, while having the outer face use a half [0,1] or [-1,0] equiangular map, so as to be compatible with the half wedges in the wave zone.

B: **angular iii** can be addressed by adding a spherical correction factor to the frustum maps that bulges them out such that the outer faces are spheres. This accomplishes the transitioning from the two inner cubes to a sphere within a single Block.

C: **angular i** can be addressed once B has been implemented by using the EquatorialCompression map (and a discrete rotation) to redistribute gridpoints from the y/z plane to the +x and -x poles. This map can be composed with the outermost spherical wedges, but must be turned off in the Blocks surrounding the black holes. The Frustum maps can be modified such that the EquatorialCompression mapping tapers off in this region. This limits the root-finding that must be performed to find an inverse to the Blocks using the Frustum map - all other Blocks in this domain use maps with analytic inverses.

Edit: **angular i** will not be addressed as described in C, as the EquatorialCompression map does not lead to a mapping that respects dtheta/dlogical = const, as the equiangular mapping does. The redistributing of the grid points will be accomplished by using the `opening_angle` argument of the Wedge along with making the enveloping cube a rectangular prism (which will have the same opening angle) and bulging out the prism into a sphere. This is done in #4934.

(Using the flat Frustum map's analytic inverse should give an excellent initial guess to the root find, I'm expecting.)

D: Independent to the above being implemented, **radial i** can be addressed through the use of maps such that zeta is mapped to an auxiliary cap_zeta that achieves the desired radial distribution. These being 1D mappings, can be more easily (relatively) implemented in place without changing much of the code.

**Comment by nilsvu** [comment]
The optimizations listed above are now implemented thanks to @mar-celine !
