### ISSUE TITLE
Ringdown: continue an evolution from common horizon

### ISSUE THREAD

**Issue by geoffrey4444** [sxs-collaboration/spectre#4600]
# Feature request:

Common horizon finding items:
- [x] DenseTrigger/Event for finding/dumping AhC.
    - This dense trigger also ideally will terminate the simulation when AhC is spherical enough, or when constraints are getting to big, as in SpEC. 
    - For now, just wait until it dies.
- [x] Store volume data when common horizon find is triggered. If no horizon is found, callback will delete the stored volume data (we don't need it). If horizon is found, then we keep the volume data.
    - For now, we know when the common horizon forms, so we can just turn on AhC + volume data output right when we need it at the end of the inspiral, after AhC forms
    - Don't delete AhC volume data for now. We can consider deleting it after we know ringdown is successful, but not necessary.

SpEC Termination criterion (not needed for q=1, zero spin BBH):
- A certain number of common horizon finds
- Constraints don't get too big
- Lmax of the common horizon gets below a threshold (is spherical enough)

Initializing ringdown domain (in post-processing script):
- [x] Dump all map coefficients
- [x] Need several AhC finds (as described above) to initialize shape and translation map coefs (and derivatives) for ringdown domain.
- [x] For shape, need #5183 .
- [x] Translation and quaternion rotation function of time are `SettleToConstant`s and cannot be updated, need #4598 #4599
- [x] Also need Expansion/Scaling #4598 #4599 and #5670
- [ ] Need to compute excision radius of new domain (degenerate with 00 component of shape map, SpEC chooses 00 component = 0). #5670
- [ ] Need c++ function that knows about old domain and new domain and does iterative procedure to find excision radius. #5670

Deal with time stepper history initialization:
- Don't. Use RK instead.
- Could use RK initially and use that to initialize history for LMS methods.

### Desired feature:

- [ ] After spectre can initialize a ringdown from common horizon initial data (#4598, #4599), combine these pieces so that the single black hole executable can successfully start the evolution.

### Detailed discussion:
Note: Until spectre can evolve to common horizon, this can be tested by interpolating SpEC data with a common horizon.

**Comment by nilsvu** [comment]
- We start with doing this in a separate executable.
- Loading numeric data already works.
- With the two separate executables we can automate initializing control systems etc. by writing a ringdown input file from measurements of the evolution. We need to initialize Strahlkorpers from a file specified in the input file.
- Use pipeline infrastructure discussed in #5021.
- To construct new map parameters we should implement the routines in C++, then call them in Python to write the ringdown input file.

**Comment by knelli2** [comment]
Updated comment today with more things to do.

**Comment by geoffrey4444** [comment]
Working for q=1, spin=0. Other issues for ringdown termination criteria and for generalizing to unequal masses.
