### ISSUE TITLE
BBH initial data

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#5425]
Collecting some remaining tasks to improve BBH initial data:

- [ ] SHK (#4515) (@asaju7 is working on this)
- [ ] AMR
- [ ] Add boost to superposed black-hole solutions (SpEC does that, but whether it helps has never been analyzed) (#5457)
- [x] Control masses and spins
- [x] Control COM (#5459)
- [x] Control ADM linear momentum (#4514)
- [x] Reduce eccentricity

For a description of lots of things that SpEC does see: http://arxiv.org/abs/1506.01689
