### ISSUE TITLE
Post-SXScon cleanup

### ISSUE THREAD

**Issue by nilsvu** [sxs-collaboration/spectre#6188]
We merged some code quickly to get ready for SXScon Aug 5--9. These things should be cleaned up afterwards:

- [ ] Add tests for https://github.com/sxs-collaboration/spectre/pull/6185
- [ ] Silence CMake and compiler warnings from https://github.com/sxs-collaboration/spectre/pull/5956
- [x] Clean up clang-tidy warnings from https://github.com/sxs-collaboration/spectre/pull/6189 (see the `files` tab on that PR)
- [x] Allowing to just use spec python scripts rather than having to build SpEC (in https://github.com/sxs-collaboration/spectre/pull/6187)
- [x] Understand and fix communication race condition in horizon finder. Appeared when BBH was run in Release mode with `SPECTRE_DEBUG` on brown cluster Oscar.
- [ ] Fix `partial_derivative` PyBinding. It currently doesn't find the type of the Jacobian correctly for the overloads which causes an error.
- [x] MacOS CI seems to be taking a lot longer lately. Possibly because of the change in ccache sloppiness in #6191 
- [x] Disable LoadBalancing from Burgers input file. It keeps failing on GCC-9. (#6210)
- [ ] Allow `plot_cce` to only take one mode. Currently it errors if only one mode is chosen (something about the legend)
- [x] In `Cce.cpp` constructor, print l_max in error message. (#6211 )
- [ ] Dump collocation points in cli or static exec
- [ ] Read collocation points in CCE
- [ ] Read multiple h5 files in CCE (combine them on the fly in a temporary file and delete the temporary afterwards)
