### ISSUE TITLE
Improvements for reading numeric ID

### ISSUE THREAD

**Issue by knelli2** [sxs-collaboration/spectre#6278]
This is specifically for the BBH, but will probably be useful for other systems as well.

- [x] Allow the ability to choose whether to set $\Pi$ and $\Phi$ from constraints or not. This will be needed for PB&J eventually and potentially also continuing to ringdown (#6430, just never set Pi/Phi for GH vars, but always set them for ADM vars)
- [x] Related to the above feature (maybe even part of it), relax restriction that all GH vars must be in the volume data. E.g. if we are specifying Pi and Phi from constraints, we should be able to put `Pi: None` and `Phi: None` since we don't need them and this won't cause an error. (also #6430 but we decided not to do this)
- [x] Add an `ObservationTimeEpsilon` so users don't have to specify the full precision time of volume data. This is needed elsewhere as well so maybe a general H5/volume subfile solution would be good. (#6296 )
- [x] Add ability to check that the domain on disk has identical h-refinement to domain in input file to allow interpolation within elements rather than across elements (important for PB&J).
